### PR TITLE
fix: non-active exchange symbols

### PR DESCRIPTION
**Pull request by habibalkhabbaz**
## Description

Based on #476 we found that the Binance API is returning all their symbols even the non-active ones.
Hence, this PR is going to squash those non-active symbols from our exchange symbols list.

## Related Issue

#476 

## How Has This Been Tested?

Write tests to check if the symbols were filtered correctly or not.

### CODE REVIEW

**Comment by chrisleekr** [comment]
Hi @habibalkhabbaz 

It can cause confusion during the time when Binance is in maintenance. 
It may remove all symbols as it's not TRADING during maintenance.

Exchange info returns the symbol status as the below link
- https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#enum-definitions

And some good summary of it. 
- https://dev.binance.vision/t/explanation-on-symbol-status/118/2

It's a bit hairy because BREAK can be just in some downtime. 

I had some thought about it. 
What if we simply allow selecting from the setting, but show the symbol status in the UI?

image

For example, if it's TRADING, then show this loading indicator. If not TRADING, show an exclamation mark with some notes.
You may have a better idea.

**Comment by habibalkhabbaz** [comment]
Hello @chrisleekr 
You are right 💯 
After reading the summary I understood that it's better to keep the symbols.

However, I think twice to make things easier :)

Besides your suggestion, what do you think about the following?

| Selecting symbols from Settings (Before)  | Selecting symbols from Settings (After) |
| ------------- | ------------- |
|   |   |
| No indicators | Green dot blinking |

I think like this will be easier to catch.

**Comment by chrisleekr** [comment]
@habibalkhabbaz that is much better idea!

**Comment by habibalkhabbaz** [comment]
Done @chrisleekr 
I also added a warning when a symbol stopped working.

**Comment by uhliksk** [comment]
@habibalkhabbaz It will be also useful to add new symbol to main screen immediatelly to be visible. Currently it is waiting for the first price change which will make this indication useless. If I add multiple inactive symbols then I even see the number of pages is incremented but selecting the last page I'll get empty screen without any indication what's wrong.

**Comment by habibalkhabbaz** [comment]
> @habibalkhabbaz It will be also useful to add new symbol to main screen immediatelly to be visible. Currently it is waiting for the first price change which will make this indication useless. If I add multiple inactive symbols then I even see the number of pages is incremented but selecting the last page I'll get empty screen without any indication what's wrong.
> 
> 
> 
> image
> 
> 

You are right @uhliksk 
We may have to call the queue whenever new symbol added.
Give me sometime to work on this.

**Comment by habibalkhabbaz** [comment]
Done @uhliksk @chrisleekr 
Now it will call `queue.executeFor` just after populating candles to mongo DB.
This will ensure that all symbols will be inserted into the `trailing-trade-cache` collection even if no ticker is received and it will show up on the frontend immediately.

**Comment by uhliksk** [comment]
Great job @habibalkhabbaz!

**Comment by chrisleekr** [comment]
@habibalkhabbaz @uhliksk 
Hey guys,

Is this ready to review/merge?

**Comment by habibalkhabbaz** [comment]
> @habibalkhabbaz @uhliksk 
> 
> Hey guys,
> 
> 
> 
> Is this ready to review/merge?

Hello @chrisleekr 
Sure, it's ready for review.

**Pull request merged**
