### PR TITLE
feat: added multiple tradingview indicators

### PR DESCRIPTION
**Pull request by chrisleekr**
## Description

This PR is providing multiple TradingView indicators. 

### Warnings: Please do a backup before upgrading. It may break due to migrations. If it breaks, please let me know. 

**Changes:**

- A migration has been added to migrate from the single TradingView to the multiple TradingView. [migrations/1664194720480-add-multiple-tradingviews.js](https://github.com/chrisleekr/binance-trading-bot/pull/539/files#diff-35266655a7ab4c0344314452fe7139e2b401c7110d8179bfc1aa6635ee3362baR1)
- Now the bot is getting multiple TradingView indicators 
  - [app/cronjob/trailingTrade/step/get-indicators.js](https://github.com/chrisleekr/binance-trading-bot/pull/539/files#diff-7ccbb93b9754d4b42354368b890277e25593218ff5a764898da3b4aeb2b9bcedR173)
  - [app/cronjob/trailingTradeIndicator/step/get-tradingview.js](https://github.com/chrisleekr/binance-trading-bot/pull/539/files#diff-0e1a8db8c37a3d9d7ab3a585dd68cf9a666168c917fd6ada597a0aefb5c8a644R193)
- When determining actions - [app/cronjob/trailingTrade/step/determine-action.js](https://github.com/chrisleekr/binance-trading-bot/pull/539/files#diff-7b3b81ac3f35b686b8003e303150b48195c16993dd3a8373ae2d587e978b8be7R397), it will check whether the bot should force to sell because the TraidingView indicators Neutral/Sell/Strong Sell. It will check all eligible interval indicators. 
- Removed override interval and TradingView recommendations when it's override action.
- When placing the buy order - [app/cronjob/trailingTrade/step/place-buy-order.js](https://github.com/chrisleekr/binance-trading-bot/pull/539/files#diff-4519c980590f37959bc31959f6d67b38d5eb50a895e5c5d693031046c451a8ccR96), it will check whether the bot can place the buy order based on the TradingView indicators Buy/Strong Buy. It will check all eligible interval indicators.
- Pass `{symbol:'global'}` to `slack.sendMessage` to make sure not flooding with duplicate messages.
- UI has been updated.

**Caveats:**
- I am limiting the number of TradingView intervals to 3 intervals. The bot will request the TradingView API endpoint extensively (it's POST - https://github.com/brian-the-dev/python-tradingview-ta/blob/main/tradingview_ta/main.py#L107). For example, if I set 3 intervals, then it will request 3 intervals * 60 seconds = 180 requests per min. I think it's already too many requests and likely blocked by TradingView. Although, they may not have any rate limit (or they do?).

## Related Issue

#438

## Motivation and Context

The TradingView is providing the indicator per interval. 
At the moment, the bot only monitors a single TradingView interval, which is ok. 
But the trend can be changed very quickly before new technical analysis results. 

## How Has This Been Tested?

It's been running on my server.
However, this requires intensive test before releasing.

## Screenshots (if appropriate):

image
image
image

### CODE REVIEW

**Comment by eppenga** [comment]
Looks cool! I also use the technique of multiple Tradingview confirmations in my own bot and have it live now for about half a year. It never gave me any problems with rate limiting. If you are interested, happy to share, but I thought this was not the place to advertise my own work :)

**Comment by chrisleekr** [comment]
@eppenga Oh, if you can share your code, I am happy to take it as a reference.
With my changes, I think there is a performance issue. Not on my server, but my server is pretty powerful to run the bot.
Raspberry Pi seems to struggle as well.

So I am thinking of refactoring the code to not harm the performance.
If you can share your code, I will definitely take a look. :)

**Comment by eppenga** [comment]
> @eppenga Oh, if you can share your code, I am happy to take it as a reference. With my changes, I think there is a performance issue. Not on my server, but my server is pretty powerful to run the bot. Raspberry Pi seems to struggle as well. My Okteto test bot is also struggling.
> 
> So I am thinking of refactoring the code to not harm the performance. If you can share your code, I will definitely take a look. :)

Sure, gladly, please see: https://github.com/eppenga/goldstar-crypto-trading-bot

It's just a simple PHP script that buys and sells based on either signals or as a gridbot. Personally I use it as a gridbot with 4-fold TradingView confirmation continuously on four different pairs and query every 15 seconds. I think the main difference regarding TradingView is that I think you query TradingView all the time and I only do so when a BUY is imminent.

So far I have never experiences issues with TradingView, not sure if they have rate limiting, never saw it.

**Comment by uhliksk** [comment]
@chrisleekr Can you add 'Force sell at ... profit is between stop-loss to trigger price?' when stop-loss is enabled? Or make it configurable relative value as maybe somebody want to accept a loss, somebody want to sell at least at zero and somebody want to sell at least to pay for a fees, I prefer the stop-loss one.

**Comment by chrisleekr** [comment]
Before merging, 
- [ ] Need to test upgrade from v0.0.98

**Comment by chrisleekr** [comment]
This PR works as expected based on the recent trades with test settings.

**Setting**
image

**Closed Trades**
image

**Charts with Buy/Sell**
image
image

**Comment by chrisleekr** [comment]
Explanation of TradingView is here - https://github.com/chrisleekr/binance-trading-bot/wiki/TradingView

**Comment by rando128** [comment]
Hi @chrisleekr, when do you plan to make it into an official 0.0.99 release?

**Comment by chrisleekr** [comment]
Hi @rando128 

I am not sure. All packages are very outdated and I will need to spend some time to update all packages.

It should work with the `main` branch if you need to use it, which is what I am doing at the moment.

**Pull request merged**
