### PR TITLE
feat: added binance market watcher service container for having estimates about your coins

### PR DESCRIPTION
**Pull request by ilbuonmarcio**
## Description

That is a followup from #308, in which I asked if there is some sort of need of automation about best and worst coin in the market, suggesting automatically if there are coins in your configuration which are doing bad and giving automatic advice about better and more profitable coins.

I created a new Docker container, using Python, Flask, Selenium and Firefox, to parse the Market Binance official page and gather data about the best and worst coins right now.
You just need to HTTP GET http://binance-market-watcher:9090/get-best-worst, and it will automatically spin up Firefox headless and gather the data for you!

## How Has This Been Tested?

It has been tested locally and on a production machine of mine.
It currently just exists as a separate entity without any integrations into the main bot interface due to waiting for suggestions about where and how to use these sort of data and what features we can add to the bot with these.
At this point in time it just spins up and is unutilized.

### CODE REVIEW

**Comment by ilbuonmarcio** [comment]
Nice, didn't know that!
I was planning on making suggestions about better coins to insert directly on the bot, or trigger warnings or notifications about new opportunities.

I was also trying to figure out if there is a way to automatically inserting more favourable coins into the bot automatically (and leave other less good coins which are currently not in a trade session) in order to try to get the best deals out of it, but the idea is still at its infancy and I'm still studying how to do that efficiently.

**Comment by chrisleekr** [comment]
Ok, that is good.

I think we better approach as small changes as possible.
But I guess we will need to decide what to do with that information first.

Possible approach:
1. Subscribe all symbols using WebSocket and save them to Redis.
    - Can Redis save that big data? Should use MongoDB? Or don't need saving at all? 
2. If gonna show data to the frontend, how will it display? 
    - Like Binance table way? Show all symbols? Or only quote assets added to the monitoring list?
 3. If gonna suggest coins, how to determine?
    - Based on what conditions to suggest? How to configure the condition?

I think the idea needs to be more concrete before adding this feature.

**Comment by ilbuonmarcio** [comment]
Yeah, fore sure...

1. Redis should be able to save that big chunk of data, we need data only for the last hour to make some sort of statistic history or so, so that should not be a problem, we will flush old data pretty frequently

3. I would suggest coins based on minimum market cap (fixed or by using a parameter) and delta percentages between ticks, and with that get the best and worst coins available based on realtime trend and current 24h delta.

2. With point 3, I'd show this sort of data, not like the Binance Market page, but with added current coins handled by the bot to give the end user a table with rankings of their coins and how they differ from best and worst coins available.


One thing for sure, we need to switch to using WebSockets and do as little and easy changes as possible, so I'll close up this pull request and open a tracking Issue for this idea, maybe directly into #308

**Comment by chrisleekr** [comment]
Yeah @ilbuonmarcio 

As you probably already know, the bot is already using WebSocket to receive the realtime candles. 

https://github.com/chrisleekr/binance-trading-bot/blob/master/app/server-binance.js

It Is just a matter of adding an extra subscription for getting all market data. 

Let's continue to think about what can do with it.

**Comment by ilbuonmarcio** [comment]
Okay, so I was discussing some days ago with @pedrohusky on Discord about this feature, and we were thinking about proceeding this way:

1) Try and save the data every 3 seconds as per your miniTicker suggestion, up to 30 minutes, and "logrotate" the data so we don't hog Redis and/or Mongo in the process
2) We group data and then show the best 10 coins in the front interface, and warn the users if their coins is at the worst end of the table (that should be easy)
3) We start making suggestions about swapping currently traded coins which are not currently in a trade with more profitable coins, with a manual trigger action in the frontend interface (that should be medium difficulty)
4) Given the previous foundations ready, we start developing on the idea of autoswapping the coins as of per 3) but without asking for human interaction, and with some criteria yet to decide precisely

Thanks for the patience and the time dedicated to this project, hope you have a nice day as always :)

**Pull request closed without merging**
