### PR TITLE
refactor: moved estimates label to open trades

### PR DESCRIPTION
**Pull request by ilbuonmarcio**
## Description

Moved estimates label to open trades, follows #305

# Screenshots
immagine

### CODE REVIEW

**Comment by ilbuonmarcio** [comment]
This could be cherry-picked or squashed, but I don't really know how to do it sadly

**Comment by chrisleekr** [comment]
Hey, I was thinking again.

I think this is a better display.
What do you think?

image

**Comment by ilbuonmarcio** [comment]
Yes indeed :)

**Comment by chrisleekr** [comment]
Ok, I will merge in.

Thanks @ilbuonmarcio !

**Comment by caebwallace** [comment]
You're too fast guys ^^

**Pull request merged**
