### PR TITLE
Correct step for "Limit price percentage" config

### PR DESCRIPTION
**Pull request by thamlth**

### CODE REVIEW

**Comment by chrisleekr** [comment]
Hey @thamlth 

Thanks for the pull request and good fix.

Can you also update for `sell.limitPercentage` and in the file `SymbolSettingIcon.js`?

**Comment by thamlth** [comment]
@chrisleekr I updated it. :)

**Comment by chrisleekr** [comment]
Hey @thamlth 

Sorry, I was not being clear. There are `sell.limitPercentage` as well in both files.
Would you mind updating those as well? :)

**Comment by chrisleekr** [comment]
Hey @thamlth 

I will merge first, I will fix the remaining one in the next update. :)

**Pull request merged**
