### PR TITLE
feat: show error when use wrong API key

### PR DESCRIPTION
**Pull request by chrisleekr**
## Description

There have been several issues opened that the bot is stuck at loading. 99% of this issue is caused by using a wrong API key. 

To provide more information, I've updated the front end to display an error message when the bot can't get account information.

## Related Issue

#538 

## Motivation and Context

As description.

## Screenshots (if appropriate):

image

### CODE REVIEW

**Comment by rando128** [comment]
@chrisleekr, did you test in dev mode?

Launching the bot for local development via `docker-compose -f docker-compose.yml up -d --build` leads to the APIError screen. 

`_.get(accountInfo, 'accountType')` is undefined.

**Comment by chrisleekr** [comment]
@rando128 
yeah? hm, let me check.

**Comment by chrisleekr** [comment]
Hm, @rando128 are you sure you configured the API key? can you check again? 
I just tested with the master branch and seems fine.

**Comment by rando128** [comment]
Yeah, that's weird. My .env has all the keys setup:

```
BINANCE_MODE=test

## Live
BINANCE_LIVE_API_KEY=...
BINANCE_LIVE_SECRET_KEY=...

## Test
BINANCE_TEST_API_KEY=...
BINANCE_TEST_SECRET_KEY=...
```

my docker-composer.yml has:
```
...
      target: dev-stage
...
      - BINANCE_MODE=test
...
```

I didn't change my setup, just pulled 0.094. And the APIError screen started to show up despite a functional environment.

If it works on your side and nobody is facing the same issue I have, I will simply hack my `LockScreen.js`.

**Comment by chrisleekr** [comment]
Yeah, I would assume you would have the correct configuration. 
You might find a bug? Not sure. Let me know if you find anything.

**Comment by peweb** [comment]
@rando128 @chrisleekr 
My bot stopped working after updating to from 094 to 0.95
I didnt change env and my API keys cant expetive because they are attached to static IP.

I double checked everything, generated new API keys but I still cant login to the bot interface and keep getting the new error screen - Failed to load your account information.

Can you please help me fix this?

Thanks!

**Comment by habibalkhabbaz** [comment]
@peweb 

There is a merged pull request https://github.com/chrisleekr/binance-trading-bot/pull/556 which solves a similar issue.
It may solve your issue too.

**Comment by rando128** [comment]
@peweb, depending on your grids status, you might be facing bug #555. It's fixed and merged in master, but not released.

**Comment by peweb** [comment]
@rando128 yes, 

image

How should I switch to master?

**Comment by rando128** [comment]
Hum, AFAIK the bot doesn't use this library. So this is something else. Check this [thread](https://stackoverflow.com/questions/74281137/solving-companion-bubble-js-error-in-the-js-console) just in case.

**Comment by peweb** [comment]
@rando128 Yeah Loom extension!
Uninstalled it and now no errors in console but I still can login to the bot. May I downgrade to 0.94?

**Comment by peweb** [comment]
@chrisleekr @rando128 
Just to let you know the master works fine. I prefer to work with docker-compose.server.yml so please, kindly release the last fixes. Thanks.

**Comment by VandrisV** [comment]
I have same issues master work fine till i loud dompose.server.yml and all stop.

**Comment by chrisleekr** [comment]
Guys, thanks for the investigation.

I will release a new version.

**Pull request merged**
