### PR TITLE
perf: bulk write candles to db

### PR DESCRIPTION
**Pull request by habibalkhabbaz**
## Description

I am so sorry about submitting a lot of PRs nowadays 😆  but believe me it's worth it.

This PR has performance improvement which uses `bulkWrite` instead of looping through all candles and insert them one by one.

## Motivation and Context

When we retrieve many candles from Binance, it will be a heavy job to save all candles one by one (many operations).
So I try to improve this with `bulkWrite` from mongo.

## How Has This Been Tested?

Tests provided

## Screenshots (if appropriate):

### CODE REVIEW

**Comment by uhliksk** [comment]
@habibalkhabbaz I'm getting this error:

```
{"name":"binance-api","version":"0.0.89","hostname":"5dd1512cdcb2","pid":46,"gitHash":"unspecified","server":"websocket","payload":{"command":"latest","authToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoZW50aWNhdGVkQXQiOiIyMDIyLTA3LTI2VDE1OjU4OjU0LjczN1oiLCJpYXQiOjE2NTg4NTExMzQsImV4cCI6MTY1ODg1ODMzNH0.2LHdWlNaI8O3GxCy6RedA6dSS5H_SWRLssyTB_LC98s","data":{"page":1,"searchKeyword":"","sortBy":"sell-profit","sortByDesc":true},"isAuthenticated":true},"level":50,"err":{"message":"Unexpected token u in JSON at position 0","name":"SyntaxError","stack":"SyntaxError: Unexpected token u in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at Object.handleLatest [as latest] (/srv/dist/server.js:1:116082)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async WebSocket.<anonymous> (/srv/dist/server.js:1:111309)"},"msg":"Something wrong with trailing-trade-common cache","time":"2022-08-18T18:36:08.381Z","v":0}
```

**Comment by habibalkhabbaz** [comment]
Hello @uhliksk 
Kindly stop the containers and pull the latest changes and then restart your container.
Keep me updated when the issue is resolved or still exist.

**Comment by uhliksk** [comment]
@habibalkhabbaz Ok, I'll try.

**Comment by uhliksk** [comment]
@habibalkhabbaz After restarting container I got:

```
{"name":"binance-api","version":"0.0.89","hostname":"07b69c23226d","pid":46,"gitHash":"unspecified","level":50,"err":{"message":"Unable to fully release the lock on resource \"redlock:trailing-trade-configurations:AVAXBUSD\".","name":"LockError","stack":"LockError: Unable to fully release the lock on resource \"redlock:trailing-trade-configurations:AVAXBUSD\".\n    at loop (/srv/node_modules/redlock/redlock.js:282:18)\n    at /srv/node_modules/redlock/redlock.js:462:10\n    at tryCatcher (/srv/node_modules/standard-as-callback/built/utils.js:12:23)\n    at /srv/node_modules/standard-as-callback/built/index.js:22:53\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"},"msg":"Unable to fully release the lock on resource \"redlock:trailing-trade-configurations:AVAXBUSD\".","time":"2022-08-18T18:48:44.442Z","v":0}
```

It looks like it is not very healthy to restart container at any time. Maybe we should do some cleanup on container start to prevent unpredictable states in database.

**Comment by habibalkhabbaz** [comment]
@uhliksk 
You are right 💯
We have to work on this in another PR.

**Comment by chrisleekr** [comment]
> I am so sorry about submitting a lot of PRs nowadays laughing but believe me it's worth it.

It's amazing, man. I really appreciate your contributions. 
This bot will not improve without your contributions. Same to you @uhliksk 


Is this ready to review? @habibalkhabbaz

**Comment by habibalkhabbaz** [comment]
@chrisleekr
Thank you. We all together doing great job.

Conflict resolved and it's ready for review as well.

**Comment by chrisleekr** [comment]
As always, looks good to me.

**Pull request merged**
